apiVersion: v1
kind: Service
metadata:
  name: beamline-nginx
  labels:
    app.kubernetes.io/name: beamline-nginx
spec:
  selector:
    app.kubernetes.io/name: beamline-nginx
  ports:
    - name: http
      port: 80
      targetPort: http
